#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.
#

#
# iSCSI initiator tasks
#
---
- name: configure iSCSI initiator
  block:
    - name: deploy iscsi-initiator-cmu.service
      template:
        src: iscsi-initiator-cmu.service.j2
        dest: /etc/systemd/system/iscsi-initiator-cmu.service

    - name: deploy iscsi-initiator-ssus.service
      template:
        src: iscsi-initiator-ssus.service.j2
        dest: /etc/systemd/system/iscsi-initiator-ssus.service

    - name: deploy iscsi-initiator-ssu1.service
      template:
        src: iscsi-initiator-ssu1.service.j2
        dest: /etc/systemd/system/iscsi-initiator-ssu1.service

    - name: deploy iscsi-initiator-ssu2.service
      template:
        src: iscsi-initiator-ssu2.service.j2
        dest: /etc/systemd/system/iscsi-initiator-ssu2.service

    - name: update systemd service configs
      systemd: daemon_reload=yes
  tags: iscsi-initiator
